version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: make init_database
    volumes:
      - static_volume:/home/app/crypto_wallet/static
      - media_volume:/home/app/crypto_wallet/media
      - redis_cache:/redis/data
    env_file:
      - .env
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started

  socketio:
    build:
      context: .
      dockerfile: Dockerfile
    command: make socketio_run
    ports:
      - "8001:8001"
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/crypto_wallet/static
      - media_volume:/home/app/crypto_wallet/media
    ports:
      - "80:80"
    depends_on:
      - web
      - socketio
      - rabbitmq



  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_volume:/data/db
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis_cache:/redis/data
    restart: always
    depends_on:
      - rabbitmq

  celery:
    restart: always
    command: make celery_run
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

networks:
  default:
    driver: bridge

volumes:
  redis_cache:
  media_volume:
  static_volume:
  postgres_volume: