"""empty message

Revision ID: 3366bbacebce
Revises: 36a9e7563001
Create Date: 2023-09-27 12:03:13.475730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = '3366bbacebce'
down_revision: Union[str, None] = '36a9e7563001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
