"""empty message

Revision ID: 36a9e7563001
Revises: 95a67b9075df
Create Date: 2023-09-13 13:19:21.223989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = '36a9e7563001'
down_revision: Union[str, None] = '95a67b9075df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    # ### end Alembic commands ###
