"""empty message

Revision ID: 57e3b47a1584
Revises: b70b5ff0b154
Create Date: 2023-08-13 09:37:08.219811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.core.database import Base
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '57e3b47a1584'
down_revision: Union[str, None] = 'b70b5ff0b154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchains')
    # ### end Alembic commands ###
