"""empty message

Revision ID: 6f7b121d1b4a
Revises: 9614e99803a6
Create Date: 2023-08-15 13:25:04.140090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = '6f7b121d1b4a'
down_revision: Union[str, None] = '9614e99803a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blockchains', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchains', type_='unique')
    # ### end Alembic commands ###
