"""empty message

Revision ID: 8bb46a3c6448
Revises: c35686194608
Create Date: 2023-08-26 13:38:43.341908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = '8bb46a3c6448'
down_revision: Union[str, None] = 'c35686194608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'orders', ['product_id'], ['id'])
    # ### end Alembic commands ###
