"""empty message

Revision ID: a44da2e03e3f
Revises: 292f66dd6c1d
Create Date: 2023-09-01 13:54:17.379283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = 'a44da2e03e3f'
down_revision: Union[str, None] = '292f66dd6c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
