"""init

Revision ID: b70b5ff0b154
Revises: 
Create Date: 2023-08-13 09:23:21.845962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = 'b70b5ff0b154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['id'])
    op.create_unique_constraint(None, 'blockchains', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'wallets', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'blockchains', type_='unique')
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
