"""empty message

Revision ID: fc2c3bcdbe19
Revises: 78bd4b477d45
Create Date: 2023-08-26 13:33:46.009144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.core.database import Base


# revision identifiers, used by Alembic.
revision: str = 'fc2c3bcdbe19'
down_revision: Union[str, None] = '78bd4b477d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.add_column('orders', sa.Column('return_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'transactions', ['return_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'return_transaction_id')
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
